### ISSUE TITLE
2.0.5 update error: lStatSync

### ISSUE THREAD

**Issue by dccirrus** [yuanchuan/find#10]
Since the last update 2.0.5 I am getting an error when trying to find files using is.symbolicLink on line 111 and then fs.lstatSync on line 53.

Reverting to 2.0.4 there are no errors.

**Comment by yuanchuan** [comment]
Sorry about that, could you please paste out the error message?

**Comment by dccirrus** [comment]
Sure, here is what I got:

Error: ENOENT: no such file or directory, lstat '../JSONStream/index.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.symbolicLink (/node_modules/find/index.js:53:19)
    at Object.fss.readlinkSync (/node_modules/find/index.js:111:27)
    at Object.fss.readlinkSync (/node_modules/find/index.js:116:16)
    at /node_modules/find/index.js:214:26
    at Array.forEach (native)

**Comment by yuanchuan** [comment]
OK，I'll try to fix it ASAP

**Comment by yuanchuan** [comment]
Fixed!  Please update to version 0.2.6

**Comment by dccirrus** [comment]
Perfect, tested it out and it works great. Thanks for the quick fix!
